# Directories
matlab_dir = $(realpath matlab)
verilog_dir = $(realpath verilog)

# Default Target
default:
all: clean report-error getdumps trace

#################################################################################################
#~	help		:	Show help message
.PHONY : help
help : Makefile
	@echo "Targets:"
	@sed -n 's/^#~//p' $<


#################################################################################################
#~	clean		:	clean all autogenerated files
.PHONY : clean
clean:
	cd $(matlab_dir) && make clean
	cd $(verilog_dir) && make clean



#################################################################################################
#~	report-error	:	generate error report

.PHONY: report-error
report-error: 
	cd $(matlab_dir) && make geterror



#################################################################################################
#~	getdumps	:	generate matlab dumps

.PHONY: getdumps
getdumps:
	@echo "Generating Matlab Dumps..."
	cd $(matlab_dir) && make getdumps



#################################################################################################
#~	verify		:	verify verilog with matlab generated dumps
.PHONY: verify
verify:
	@echo "verifying Verilog..."
	cd $(verilog_dir) && make verify



#################################################################################################
#~	trace		:	generate VCD trace
.PHONY: trace
trace:
	@echo "Generating VCD trace..."	
	cd $(verilog_dir) && make verify ENABLE_TRACE=True
